kind: pipeline
name: pipeline1

steps:
- name: P1-S1
  image: alpine/git
  user: root
  volumes:
    - name: test-dir
      path: /builds
  commands:
  - mkdir /builds/build_${DRONE_BUILD_NUMBER}
  - echo "testfile_${DRONE_BUILD_NUMBER}" > /builds/build_${DRONE_BUILD_NUMBER}/test_${DRONE_BUILD_NUMBER}.txt
  - ls -la /builds/build_${DRONE_BUILD_NUMBER}
  - sleep 2

volumes:
  - name: test-dir
    host:
      path: /ci-share

---

kind: pipeline
name: pipeline2

steps:
- name: P2-S1
  image: alpine/git
  user: root
  commands:
  - sleep 3
  - exit 0

- name: P2-S2
  image: alpine/git
  user: root
  commands:
  - sleep 2

- name: P2-S3
  image: alpine/git
  user: root
  volumes:
    - name: test-dir
      path: /builds
  commands:
  - sleep 2
  - ls -la /builds/build_${DRONE_BUILD_NUMBER}
  - cat /builds/build_${DRONE_BUILD_NUMBER}/test_${DRONE_BUILD_NUMBER}.txt

depends_on:
  - pipeline1

volumes:
  - name: test-dir
    host:
      path: /ci-share

---

kind: pipeline
name: pipeline3

steps:
- name: P3-S1
  image: alpine/git
  user: root
  commands:
  - sleep 2

- name: P3-S2
  image: alpine/git
  user: root
  commands:
  - sleep 2

- name: P3-S3
  image: alpine/git
  user: root
  volumes:
    - name: test-dir
      path: /builds
  commands:
  - sleep 2
  - cat /builds/build_${DRONE_BUILD_NUMBER}/test_${DRONE_BUILD_NUMBER}.txt

depends_on:
  - pipeline1

volumes:
  - name: test-dir
    host:
      path: /ci-share

---

kind: pipeline
name: pipeline4

steps:
- name: P4-S1
  image: alpine/git
  user: root
  commands:
  - sleep 2

depends_on:
  - pipeline1
  - pipeline3

---
# this pipeline should execute as last and should ignore failing pipelines
kind: pipeline
name: cleanup-pipeline

steps:
- name: quote-cleanup-endquote
  image: alpine/git
  user: root
  volumes:
    - name: test-dir
      path: /builds
  commands:
  - cat /builds/build_${DRONE_BUILD_NUMBER}/test_${DRONE_BUILD_NUMBER}.txt
  - sleep 2

depends_on:
  - pipeline1

volumes:
  - name: test-dir
    host:
      path: /ci-share