kind: pipeline
name: pipeline1

steps:
- name: P1-S1
  image: alpine/git
  commands:
  - mkdir drone-cache
  - echo "testfile_${DRONE_BUILD_NUMBER}" > ./drone-cache/test_${DRONE_BUILD_NUMBER}.txt
  - ls -la drone-cache
  - sleep 2

- name: P1-S2
  image: alpine/git
  commands:
  - ls -la /drone/src
  - ls -la /drone/src/drone-cache

- name: rebuild-cache
  image: meltwater/drone-cache
  pull: true
  environment:
    SFTP_USERNAME:
      from_secret: sftp_username
    SFTP_PASSWORD:
      from_secret: sftp_password
    SFTP_AUTH_METHOD: PASSWORD
    SFTP_HOST: 116.202.128.230
    SFTP_PORT: 2732
    SFTP_CACHE_ROOT: "/upload"
  settings:
    rebuild: true
    debug: true
    backend: "sftp"
    cache_key: '{{ .Repo.Name }}-build-{{ .Build.Number }}'
    mount:
      - 'drone-cache' # <- builds a cache from this directory

# ---

# kind: pipeline
# name: pipeline1-2

# steps:
# - name: P1-2-S1
#   image: alpine/git
#   user: root
#   volumes:
#     - name: test-dir
#       path: /builds
#   commands:
#   - mkdir /builds/build_${DRONE_BUILD_NUMBER}_2
#   - echo "testfile_${DRONE_BUILD_NUMBER}_2" > /builds/build_${DRONE_BUILD_NUMBER}_2/test_${DRONE_BUILD_NUMBER}_2.txt
#   - chown -R nobody:nogroup /builds/build_${DRONE_BUILD_NUMBER}_2
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}_2
#   - sleep 2

# volumes:
#   - name: test-dir
#     host:
#       path: /mnt/ci-share

---

kind: pipeline
name: pipeline2

steps:

- name: prepare-restored-cache-dir
  image: alpine/git
  volumes:
    - name: cache
      path: /drone/drone-cache
  commands:
  - mkdir /drone/drone-cache/drone-cache

- name: restore-cache
  image: meltwater/drone-cache
  pull: true
  volumes:
    - name: cache
      path: /drone/drone-cache
  environment:
    SFTP_USERNAME:
      from_secret: sftp_username
    SFTP_PASSWORD:
      from_secret: sftp_password
    SFTP_AUTH_METHOD: PASSWORD
    SFTP_HOST: 116.202.128.230
    SFTP_PORT: 2732
    SFTP_CACHE_ROOT: "/upload"
  settings:
    restore: true
    debug: true
    backend: "sftp"
    cache_key: '{{ .Repo.Name }}-build-{{ .Build.Number }}'
    mount:
      - '/drone/drone-cache'

- name: P2-S1
  image: alpine/git
  commands:
  - sleep 3
  - exit 0

- name: P2-S2
  image: alpine/git
  commands:
  - sleep 2

- name: P2-S3
  image: alpine/git
  volumes:
    - name: cache
      path: /drone/drone-cache
  commands:
  - sleep 2
  - ls -la /drone/drone-cache/cache
  - cat /drone/drone-cache/cache/test_${DRONE_BUILD_NUMBER}.txt
  # - ls -la /builds/build_${DRONE_BUILD_NUMBER}_2
  # - cat /builds/build_${DRONE_BUILD_NUMBER}_2/test_${DRONE_BUILD_NUMBER}_2.txt

depends_on:
  - pipeline1
  # - pipeline1-2

volumes:
  - name: cache
    temp: {}

# ---

# kind: pipeline
# name: pipeline3

# steps:
# - name: P3-S1
#   image: alpine/git
#   user: root
#   commands:
#   - sleep 2

# - name: P3-S2
#   image: alpine/git
#   user: root
#   commands:
#   - sleep 2

# - name: P3-S3
#   image: alpine/git
#   user: root
#   volumes:
#     - name: test-dir
#       path: /builds
#   commands:
#   - sleep 2
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}
#   - cat /builds/build_${DRONE_BUILD_NUMBER}/test_${DRONE_BUILD_NUMBER}.txt
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}_2
#   - cat /builds/build_${DRONE_BUILD_NUMBER}_2/test_${DRONE_BUILD_NUMBER}_2.txt

# depends_on:
#   - pipeline1
#   - pipeline1-2

# volumes:
#   - name: test-dir
#     host:
#       path: /mnt/ci-share

# ---

# kind: pipeline
# name: pipeline4

# steps:
# - name: P4-S1
#   image: alpine/git
#   user: root
#   volumes:
#     - name: test-dir
#       path: /builds
#   commands:
#   - sleep 2
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}
#   - cat /builds/build_${DRONE_BUILD_NUMBER}/test_${DRONE_BUILD_NUMBER}.txt
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}_2
#   - cat /builds/build_${DRONE_BUILD_NUMBER}_2/test_${DRONE_BUILD_NUMBER}_2.txt
#   - exit 1

# depends_on:
#   - pipeline1
#   - pipeline1-2

# volumes:
#   - name: test-dir
#     host:
#       path: /mnt/ci-share

# ---

# kind: pipeline
# name: pipeline5

# steps:
# - name: P5-S1
#   image: alpine/git
#   user: root
#   volumes:
#     - name: test-dir
#       path: /builds
#   commands:
#   - sleep 2
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}
#   - cat /builds/build_${DRONE_BUILD_NUMBER}/test_${DRONE_BUILD_NUMBER}.txt
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}_2
#   - cat /builds/build_${DRONE_BUILD_NUMBER}_2/test_${DRONE_BUILD_NUMBER}_2.txt

# depends_on:
#   - pipeline1
#   - pipeline1-2

# volumes:
#   - name: test-dir
#     host:
#       path: /mnt/ci-share

# ---

# kind: pipeline
# name: pipeline6

# steps:
# - name: P6-S1
#   image: alpine/git
#   user: root
#   volumes:
#     - name: test-dir
#       path: /builds
#   commands:
#   - sleep 2
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}
#   - cat /builds/build_${DRONE_BUILD_NUMBER}/test_${DRONE_BUILD_NUMBER}.txt
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}_2
#   - cat /builds/build_${DRONE_BUILD_NUMBER}_2/test_${DRONE_BUILD_NUMBER}_2.txt

# depends_on:
#   - pipeline1
#   - pipeline1-2

# volumes:
#   - name: test-dir
#     host:
#       path: /mnt/ci-share
# ---

# kind: pipeline
# name: pipeline7

# steps:
# - name: P7-S1
#   image: alpine/git
#   user: root
#   volumes:
#     - name: test-dir
#       path: /builds
#   commands:
#   - sleep 2
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}
#   - cat /builds/build_${DRONE_BUILD_NUMBER}/test_${DRONE_BUILD_NUMBER}.txt
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}_2
#   - cat /builds/build_${DRONE_BUILD_NUMBER}_2/test_${DRONE_BUILD_NUMBER}_2.txt

# depends_on:
#   - pipeline1
#   - pipeline1-2

# volumes:
#   - name: test-dir
#     host:
#       path: /mnt/ci-share

# ---

# kind: pipeline
# name: pipeline8

# steps:
# - name: P8-S1
#   image: alpine/git
#   user: root
#   volumes:
#     - name: test-dir
#       path: /builds
#   commands:
#   - sleep 2
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}
#   - cat /builds/build_${DRONE_BUILD_NUMBER}/test_${DRONE_BUILD_NUMBER}.txt
#   - ls -la /builds/build_${DRONE_BUILD_NUMBER}_2
#   - cat /builds/build_${DRONE_BUILD_NUMBER}_2/test_${DRONE_BUILD_NUMBER}_2.txt

# depends_on:
#   - pipeline1
#   - pipeline1-2

# volumes:
#   - name: test-dir
#     host:
#       path: /mnt/ci-share