kind: pipeline
name: pipeline1

steps:
- name: P1-S1
  image: alpine/git
  user: root
  volumes:
    - name: test-dir
      path: /builds
  commands:
  - mkdir /builds/build_${DRONE_BUILD_NUMBER}
  - echo "testfile" > /builds/build_${DRONE_BUILD_NUMBER}/test.txt
  - ls -la /builds/build_${DRONE_BUILD_NUMBER}

volumes:
  - name: test-dir
    host:
      path: /usr/local/etc/tezedge-ci/build/

---

kind: pipeline
name: pipeline2

steps:
- name: P2-S1
  image: alpine/git
  user: root
  commands:
  - sleep 30
  - exit 1

- name: P2-S2
  image: alpine/git
  user: root
  commands:
  - sleep 2

depends_on:
  - pipeline1

---

kind: pipeline
name: pipeline3

steps:
- name: P3-S1
  image: alpine/git
  user: root
  commands:
  - sleep 2

- name: P3-S2
  image: alpine/git
  user: root
  commands:
  - sleep 2

- name: P3-S3
  image: alpine/git
  user: root
  commands:
  - sleep 2

---

kind: pipeline
name: pipeline4

steps:
- name: P4-S1
  image: alpine/git
  user: root
  commands:
  - sleep 2

depends_on:
  - pipeline1
  - pipeline3

---
# this pipeline should execute as last and should ignore failing pipelines
kind: pipeline
name: cleanup-pipeline

steps:
- name: quote-cleanup-endquote
  image: alpine/git
  user: root
  commands:
  - sleep 2

when:
  status:
  - success
  - failure

depends_on:
  - pipeline1
  - pipeline2
  - pipeline3
  - pipeline4